os:
  - linux
  - osx
language: node_js
sudo: false
node_js:
  - '9'
  - '10'

before_install:
  - yarn config set ignore-engines true
  - yarn global add mocha
  - yarn global add lerna

install:
  - yarn --network-timeout 600000
  - lerna bootstrap

script:
  - yarn test

cache:
  - node_modules -> yarn.lock